### ISSUE TITLE
Commands not executed on Windows

### ISSUE THREAD

**Issue by lobneroO** [Dax89/automaton.nvim#10]
I had hoped fixing the [globals issue](https://github.com/Dax89/automaton.nvim/issues/7) would solve this, but sadly it doesn't.

On Windows, commands are not executed. They are printed into a terminal, but they don't do anything.

Also, when trying to execute, it will do so just once. I can close the terminal afterwards and call up the same task again, but now not even the terminal gets opened anymore until I restart nvim.

There is no output that I can see at all (apart from terminal the first time)

https://github.com/Dax89/automaton.nvim/assets/17877050/f095d3a2-7a7d-435a-9715-a871565f68bf

I tested this in Windows Terminal on both Powershell and Git-Bash. In WSL, it works, but also only once. On my Arch Linux system, I didn't notice any such problems.

**Comment by Dax89** [comment]
Can I see `tasks.json`?

So the command is executed only once? In `runner.lua` there is a "jobs map" which prevents to execute the same command if it's still running, maybe (for some reason) it's not cleared when the task is completed.

**Comment by lobneroO** [comment]
I have tried it in both a C++ and a Rust project

Rust:
```
{
    version: "1.0.0",

    tasks: [
        {
            name: "build",
            type: "shell",
            default: "true",
            command: "cargo build",
            quickfix: true,
            compiler: "cargo",
        }
    ]
}
```

C++
```
{
    version: "1.0.0",

    tasks: [
        {
            name: "test",
            cwd: "${workspace_folder}",
            type: "shell"
            command: "cmake -S . -B build"
        }
    ]
}
```

I'll look at the runner when I find the time

**Comment by Dax89** [comment]
I'm setting up a VM with windows 10 so I can check if I find something this weekend.

**Comment by lobneroO** [comment]
I put some time into debugging this. The issue seems that `vim.fn.jobstart` never seems to finish (or perhaps even start?). Right now, I don't know how to debug this further.
I use git-bash on Windows as my nvim shell, but I also tried Powershell. Same (lack of) effect.

I don't think the terminal itself is the problem though. I use [toggleterm](https://github.com/akinsho/toggleterm.nvim) as well and I can execute commands in it.

**Comment by Dax89** [comment]
I have finally installed a VM with Windows 10 and did a simple neovim configuration (lazy + automation).
It looks fine both in launch and tasks configuration, is there maybe some edge case that it's not considered?

I have tested these configs:
```json5
// launch.json
{
    version: "1.0.0",

    configurations: [
        {
            name: "test launch",
            cwd: "${workspace_folder}",
            type: "shell",
            program: "nvim",
            args: ["-h"],
            default: true
        }
    ]
}

// tasks.json
{
    version: "1.0.0",

    tasks: [
        {
            name: "test task",
            cwd: "${workspace_folder}",
            type: "shell",
            command: "clangd --version",
            default: true
        }
    ]
}
```

NeoVim config (basically the one you find [here](https://lazy.folke.io/installation)):

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

require("lazy").setup({
    spec = {
        {
            "Dax89/automaton.nvim",  
            dependencies = {
                "nvim-lua/plenary.nvim",
                "nvim-telescope/telescope.nvim",
            }

            config = true
        }
    },

    install = { colorscheme = { "habamax" } },
    checker = { enabled = true },
})

```

**Comment by lobneroO** [comment]
There is a missing ',' after the closing brace of the automaton dependencies.

Both `:Automaton tasks default` and `:Automaton launch default` try to open /usr/bin/bash (which of course doesn't exist on Windows). That being said, they didn't become unresponsive the same way they did in my original problem.

I added the following to the init.lua to target git-bash instead:

```
-- ...
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- share the clipboard with the system
vim.opt.clipboard = 'unnamedplus'
vim.cmd [[let &shell = '"C:/Program Files/Git/bin/bash.exe"']]
vim.cmd [[let &shellcmdflag = '-s']]

require("lazy").setup({

-- ...
```

And this already introduced the problem. Which shell did you default to on your VM?
You can get the git-bash through the default git installer, it will ask you about installing it at some point.
I assume it won't be necessary, given that this minimal thing can reproduce the issue for me. But just in case, here is my full config:
https://github.com/lobneroO/nvim_conf

Also, I am on Windows 11.

**Comment by Dax89** [comment]
> There is a missing ',' after the closing brace of the automaton dependencies.

Ooops, I'm writing the code manually by reading the VM :D

>  Which shell did you default to on your VM?

It's a vanilla windows 10 so I assume that is the good old `cmd.exe`


I have made some tests and I come across your bug: basically the job stays pending because the shell  just opens and waits for inputs.

I have changed your shell options as:

```
vim.cmd [[let &shell='"C:\Program Files\Git\bin\bash.exe"'']]
vim.cmd [[set shellcmdflag='-c']]
vim.cmd [[set shellxquote=]]
vim.cmd [[set shellxescape=]]
```

And it looks like it works.

**EDIT**: I have found the options here: https://github.com/neovim/neovim/issues/28384#issuecomment-2135921829

**Comment by lobneroO** [comment]
I looks like changing the `shellcmdflag` from `-s` to `-c` is important. I did this originally because others suggested it for git-bash specifically, but at first glance the terminal itself still works. Therefore I think this is fixed and hope I don't run into follow up problems. Thank you for having a look

**Comment by Dax89** [comment]
If there are any problems (even related to this one) feel free to open other issues!
