### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by lobneroO** [Dax89/automaton.nvim#5]
The documentation is a bit lacking, it's hard to use the plugin.

E.g. what is the difference between Automaton Create and Automaton Init? Why does create -> enter name "xyz" give a prompt of "xyz/home/user"?

I tried to initialize a workspace in one of my rust projects and it didn't give an error, but I don't see the .json files. Do I have to manually create them? What did init do then?

**Comment by Dax89** [comment]
There is some basic documentation here: https://github.com/Dax89/automaton.nvim/wiki

- Automaton Create: It's like "New Project", you need to insert a name and select a folder where the project will be created.
- Automaton Init: Creates a workspace in neovim's current directory (workspaces are detected by the presence of `.automaton` folder), it's useful for create an automaton workspace for an existing project.

Here you can find some informations about a workspace: https://github.com/Dax89/automaton.nvim/wiki/Workspace

**Comment by lobneroO** [comment]
Ah, that latter link was what I was looking for, thank you. I'll see if this already sufficient. I think it would be beneficial to link to that page in this repositories readme

**Comment by Dax89** [comment]
I have checked the source code,  `Automaton init` creates a workspace in the folder that belongs to the currently open file.

So if you have:
```
foo/
  bar/
    main.rs
```

And you have `main.rs` open, the result is:
```
foo/
  bar/
    .automaton/ <==== this is where all workspace data is stored
    main.rs
```
