### ISSUE TITLE
build task for quick fix list

### ISSUE THREAD

**Issue by lobneroO** [Dax89/automaton.nvim#8]
Sorry about opening 99% of your issues :)

I am just getting into the quickfix list. It's super useful to jump around it when having compile errors, so I'd like to start using it. From what I can see, there is a pattern in the gcc template, but when programming in Rust I do not really need that; neovim knows cargo as a compiler type. So is there a way to set ":compiler cargo" and pipe the build output to the quickfix list?

**Comment by Dax89** [comment]
> Sorry about opening 99% of your issues :)

Don't worry!

> I am just getting into the quickfix list. It's super useful to jump around it when having compile errors, so I'd like to start using it. From what I can see, there is a pattern in the gcc template, but when programming in Rust I do not really need that; neovim knows cargo as a compiler type. So is there a way to set ":compiler cargo" and pipe the build output to the quickfix list?

Nice, I didn't know this command!
Yes I can add that, it will be something like:

```json5
{
  ...
  compiler: "cargo", // or every value supported by :command
  ...
}
```

PS: I've noticed that there is also `gcc`, so I can remove the custom pattern!

**Comment by Dax89** [comment]
I have added the `compiler` option, let me know if it works!

**Comment by lobneroO** [comment]
Quickfix list works like a charm, thank you very much. I noticed there is no colored output when building - I'm not sure there was some before, but I think so. That may also stem from my setup though, as before it was a terminal giving output and now it's the quickfix list I guess?

**Comment by Dax89** [comment]
It depends, terminal mode have the same color like if you are running the command from...a terminal.

You can have both modes, it depends on what you need.
The default mode il `terminal`, if you want the output in a quickfix list add `quickfix: true`

**Comment by lobneroO** [comment]
I have that `quickfix: true` part, which is what I meant that it works. It just doesn't display the output colored. However, calling `:copen` opens the quickfix list with coloured output. If I have seen this correctly, that's exactly the method automaton calls to open the quick fix list, so I don't know what's up there. Either way, you added support as requested, so thanks again :)
